#!/usr/bin/env bash
# Display "To infinity and beyond" indefinitely and resist SIGTERM

# Trap SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done

